name: matn_uzz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_screenutil: ^5.1.1
  flutter_svg: ^1.0.3
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
